### Login
# @name login
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "username": "username1",
    "password": "loremipsum"
}


### Variables
@accessToken = {{login.response.body.data.token}}

### Find all products
GET {{base_url}}/products
Authorization: Bearer {{accessToken}}

### Find products with search filter only
GET {{base_url}}/products?search=eggs
Authorization: Bearer {{accessToken}}

### Find products with status filter only
GET {{base_url}}/products?status=in_stock
Authorization: Bearer {{accessToken}}

### Find products with category filter only
GET {{base_url}}/products?category=Fruits
Authorization: Bearer {{accessToken}}

### Find products with min price filter only
GET {{base_url}}/products?min_price=10
Authorization: Bearer {{accessToken}}

### Find products with max price filter only
GET {{base_url}}/products?max_price=1
Authorization: Bearer {{accessToken}}

### Find product with min and max price filter only
GET {{base_url}}/products?min_price=10&max_price=16
Authorization: Bearer {{accessToken}}

### Find products with combined filters
GET {{base_url}}/products?search=eggs&status=in_stock&category=Fruits&min_price=10&max_price=10
Authorization: Bearer {{accessToken}}

### Delete product by id
DELETE {{base_url}}/products/00000000-0000-0000-0000-000000000000
Authorization: Bearer {{accessToken}}
