### Login
# @name login
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "username": "username1",
    "password": "loremipsum"
}

### Variables
@accessToken = {{login.response.body.data.token}}


### Get current user
GET  {{base_url}}/user/me
Authorization: Bearer {{accessToken}}

### Get all users
GET {{base_url}}/user
Authorization: Bearer {{accessToken}}